# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2
        with:
              # Optional SDK version to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
              dotnet-version: 5.0.x
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2
        with:
          # Optional SDK version to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: 5.0.x
      - name: dotnet build
        run: dotnet build -c release
      - name: docker build
        run: docker build -t aksapp:'${{github.sha}}' .
      - name: docker login
        run: docker login --username '${{secrets.DOCKER_ID}}' --password '${{secrets.DOCKER_PASSWORD}}'
      - name: tag docker image
        run: docker tag aksapp:'${{github.sha}}' '${{secrets.DOCKER_ID}}'/aksapp:'${{github.sha}}'
      - name: push docker image
        run: docker push '${{secrets.DOCKER_ID}}'/aksapp:'${{github.sha}}'
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1.1
        with:
          # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
          creds: '${{secrets.AZURE_CREDENTIALS}}'
          # Resource Group Name
          resource-group: aksrg
          # AKS Cluster Name
          cluster-name: demoAKSClustor 
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1
        with:                 
          manifests: |
            k8s/aksapp-deployment.yaml
            k8s/loadbalancer.yaml          
          images: '${{secrets.DOCKER_ID}}/aksapp:${{github.sha}}'                
          action: deploy
